/** Declaration file generated by dts-gen */

export class Strategy {
    constructor(options: any, verify: any);

    userProfile(accessToken: any, done: any): any;

}

export const version: string;

export namespace Strategy {
    namespace aprototype {
        function authenticate(req: any, options: any): any;

        function authorizationParams(options: any): any;

        function userProfile(accessToken: any, done: any): any;

        namespace authenticate {
            const aprototype: {
            };

        }

        namespace authorizationParams {
            const aprototype: {
            };

        }

        namespace userProfile {
            const aprototype: {
            };

        }

    }

}

